//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LmBookManager.h
//  @ Date : 2009-01-11
//  @ Author : 
//
//


#if !defined(_LMBOOKMANAGER_H)
#define _LMBOOKMANAGER_H
#include <iostream>
#include "LmContent.h"

class LmBookManager {
public:
	LmBookManager();
	~LmBookManager();

	LmContent* m_pListBook;
	bool RegisterBook();
	bool UnregisterBook();
	LmContent* GetBook(string _bookName);
private:
	bool UnregisterAllBook();
};

#endif  //_LMBOOKMANAGER_H
