//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LmContent.h
//  @ Date : 2009-01-11
//  @ Author : 
//
//


#if !defined(_LMCONTENT_H)
#define _LMCONTENT_H

#include <string>

using namespace std;

class LmContent {
public:
	LmContent()
	{
		m_pPrev = NULL;
		m_pNext = NULL;
	}
	string m_strTitle;
	string m_strAuthor;
	string m_strPublisher;
	int m_iPrice;
	string m_strKind;
	string m_strSummary;
	string m_strMemo;
	string m_strUser;
	LmContent* m_pPrev;
	LmContent* m_pNext;
};

#endif  //_LMCONTENT_H
