//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LmDataCenter.h
//  @ Date : 2009-01-11
//  @ Author : 
//
//


#if !defined(_LMDATACENTER_H)
#define _LMDATACENTER_H

#include <iostream>
#include "LmBookManager.h"
#include "LmUser.h"

class LmDataCenter {
private:
	LmBookManager* m_pBookManger;
public:
	LmDataCenter();
	~LmDataCenter();
	void Run();
private:
	int SelectMenu();
	void SearchBook();
	void RegisterBook();
	void UnregisterBook();
};

#endif  //_LMDATACENTER_H
