//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LmDataCenter.cpp
//  @ Date : 2009-01-11
//  @ Author : 
//
//


#include "LmDataCenter.h"
LmDataCenter::LmDataCenter()
{
	m_pBookManger = new LmBookManager;
}

LmDataCenter::~LmDataCenter()
{
	delete m_pBookManger;
	m_pBookManger = NULL;
}

void LmDataCenter::Run()
{
	int SelectNum = -1;
	while(SelectNum != 0)
	{
		SelectNum = SelectMenu();
		switch(SelectNum)
		{
		case 1:
			SearchBook();
			break;
		case 2:
			RegisterBook();
			break;
		case 3:
			UnregisterBook();
			break;
		}
	}
}

int LmDataCenter::SelectMenu() 
{
	int InputNum;
	while(true)
	{
		cout << "------------------------------" << endl;
		cout << "       마이 데이터 센터       " << endl;
		cout << "------------------------------" << endl;
		cout << "         1.  책  검색         " << endl;
		cout << "         2.  책  등록         " << endl;
		cout << "         3.  책  삭제         " << endl;
		cout << "         0.  종  료           " << endl;
		cout << "------------------------------" << endl;
		cout << "메뉴 번호 입력 : ";
		cin >> InputNum;

		if((InputNum > 3)||(0 > InputNum))
			cout << "잘못된 입력입니다. 다시 입력해 주세요."<< endl;
		else
			return InputNum;
	}
}

void LmDataCenter::SearchBook()
{
	string strBookTitle;
	LmContent* pBook = NULL;

	cout << "찾을 책 제목 : ";
	cin >> strBookTitle;

	pBook = m_pBookManger->GetBook(strBookTitle);
	if(pBook == NULL)
	{
		cout << "찾는 책이 없습니다." << endl;
		return;
	}

	cout << "책 제목 : " << pBook->m_strTitle << endl;
	cout << "책 출판사 : " << pBook->m_strPublisher << endl;
	cout << "책 저자 : " << pBook->m_strAuthor << endl;
}

void LmDataCenter::RegisterBook()
{
	if(m_pBookManger->RegisterBook())
		cout << "책 등록을 하였습니다. " << endl;
	else
		cout << "책 등록에 실패하였습니다. " << endl;
}

void LmDataCenter::UnregisterBook()
{
	if(m_pBookManger->UnregisterBook())
		cout << "삭제 되었습니다. " << endl;
	else
		cout << "삭제할 책을 찾을 수 없습니다. " << endl;
}
