//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LmDate.h
//  @ Date : 2009-01-11
//  @ Author : 
//
//


#if !defined(_LMDATE_H)
#define _LMDATE_H


class LmDate {
public:
	int m_iYear;
	int m_iMonth;
	int m_iDay;
};

#endif  //_LMDATE_H
