//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LmDiary.cpp
//  @ Date : 2009-01-11
//  @ Author : 
//
//


#include "LmDiary.h"

bool LmDiary::WritePaper() {

	return false;
}

bool LmDiary::RemovePager(int _pageNumber) {

	return false;
}

