//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LmDiary.h
//  @ Date : 2009-01-11
//  @ Author : 
//
//


#if !defined(_LMDIARY_H)
#define _LMDIARY_H

#include "LmPage.h"

class LmDiary {
public:
	LmPage m_listPaper;
	string m_strUser;
	bool WritePaper();
	bool RemovePager(int _pageNumber);
};

#endif  //_LMDIARY_H
