//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LmDVDManager.h
//  @ Date : 2009-01-11
//  @ Author : 
//
//


#if !defined(_LMDVDMANAGER_H)
#define _LMDVDMANAGER_H

#include "LmContent.h"

class LmDVDManager {
public:
	LmContent m_listDVD;
	bool RegisterDVD();
	bool UnregisterDVD();
	LmContent* GetDVD(string _DVDName);
};

#endif  //_LMDVDMANAGER_H
