//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LmDVD.h
//  @ Date : 2009-01-11
//  @ Author : 
//
//


#if !defined(_LMDVD_H)
#define _LMDVD_H


class LmDVD {
public:
	string m_strTitle;
	string m_strAuthor;
	string m_strPublisher;
	int m_iPrice;
	string m_strKind;
};

#endif  //_LMDVD_H
