//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LmDVDManager.cpp
//  @ Date : 2009-01-11
//  @ Author : 
//
//


#include "LmDVDManager.h"

bool LmDVDManager::RegisterDVD() {

	return false;
}

bool LmDVDManager::UnregisterDVD() {

	return false;
}

LmContent* LmDVDManager::GetDVD(string _DVDName) {

	return NULL;
}

