//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LmUser.cpp
//  @ Date : 2009-01-11
//  @ Author : 
//
//


#include "LmUser.h"

bool LmUser::LentBook(string _strBookName) {

	return false;
}

bool LmUser::LentDVD(string _strDVDName) {

	return false;
}


