//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LmUser.h
//  @ Date : 2009-01-11
//  @ Author : 
//
//


#if !defined(_LMUSER_H)
#define _LMUSER_H

#include <string>
#include "LmDate.h"

using namespace std;

class LmUser {
public:
	int m_strName;
	int m_strPhoneNumber;
	LmDate m_dateBirthDay;
	int m_strAddress;
	int m_strPassword;
	int m_strEmail;
	int m_listLentBook;
	int m_listLentDVD;
	int m_listLentDiary;
	bool LentBook(string _strBookName);
	bool LentDVD(string _strDVDName);
};

#endif  //_LMUSER_H
