//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LmWeather.h
//  @ Date : 2009-01-11
//  @ Author : 
//
//


#if !defined(_LMWEATHER_H)
#define _LMWEATHER_H


enum LmWeather {
	CLOUD,
	RAIN,
	HOT,
	COLD,
	COOL,
	WARM
};

#endif  //_LMWEATHER_H
